### ISSUE TITLE
[Google Cloud] Add option to change service code in collector plugin

### ISSUE THREAD

**Issue by jihyungSong** [spaceone-dev/plugin-google-cloud-inven-collector#1]
```
options: 
  service_code_mapper: 
    AmazonEC2: Amazon Elastic Computing
    ...
```
